version: '3.8'

services:
  todo-app:
    container_name: api
    build: ./
    command: ["./cmd/wait-for-postgres.sh", "db", "./todo-app"]
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=qwerty
  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=todo-app
    ports:
      - 5436:5432
